---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    image_id: ami-fb68f8cb # canoical ami for us-west-2

suites:
- name: default
  run_list:
    - recipe[apt]
    - recipe[bluepill_devel]
